In [1]:
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'
data = pd.read_csv(url, sep=';')

In [5]:
data.isnull().sum()

Tipo              0
Bairro            0
Quartos           0
Vagas             0
Suites            0
Area              0
Valor            17
Condominio     4093
IPTU          10237
dtype: int64

In [7]:
data = data.fillna(0)

In [8]:
data

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,0.0
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

creating numeric column

In [9]:
data['Valor_por_mes'] = data['Valor'] + data['Condominio']

In [11]:
data['Valor_por_ano'] = (data['Valor'] * 12) + (data['Condominio'] * 12) + data['IPTU']

creating categoric column

In [24]:
data['Descricao'] = data['Tipo'] + ' em ' + data['Bairro'] + ' com ' + \
                                        data['Quartos'].astype(str) + ' quarto(s) ' + \
                                        ' e ' + data['Vagas'].astype(str) + ' vaga(s) de garagem.'

In [25]:
data

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor_por_mes,Valor_por_ano,Descricao
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,2200.0,26460.0,Quitinete em Copacabana com 1 quarto(s) e 0 v...
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0,7000.0,84000.0,Casa em Jardim Botânico com 2 quarto(s) e 0 v...
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0,9220.0,111751.0,Conjunto Comercial/Sala em Barra da Tijuca com...
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,1190.0,14300.0,Apartamento em Centro com 1 quarto(s) e 0 vag...
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0,1030.0,12360.0,Apartamento em Higienópolis com 1 quarto(s) e...
...,...,...,...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0,1150.0,13825.0,Quitinete em Centro com 0 quarto(s) e 0 vaga(...
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0,2600.0,31240.0,Apartamento em Jacarepaguá com 3 quarto(s) e ...
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0,1909.0,22945.0,Apartamento em São Francisco Xavier com 2 quar...
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,0.0,3760.0,45120.0,Apartamento em Leblon com 2 quarto(s) e 0 vag...
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0,10706.0,129581.0,Conjunto Comercial/Sala em Centro com 0 quarto...

creating binary column

In [27]:
data['Possui_suite'] = data['Suites'].apply(lambda x: "Sim" if x > 0 else "Não")

In [28]:
data.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor_por_mes,Valor_por_ano,Descricao,Possui_suite
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,2200.0,26460.0,Quitinete em Copacabana com 1 quarto(s) e 0 v...,Não
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0,7000.0,84000.0,Casa em Jardim Botânico com 2 quarto(s) e 0 v...,Sim
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0,9220.0,111751.0,Conjunto Comercial/Sala em Barra da Tijuca com...,Não
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,1190.0,14300.0,Apartamento em Centro com 1 quarto(s) e 0 vag...,Não
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0,1030.0,12360.0,Apartamento em Higienópolis com 1 quarto(s) e...,Não

In [29]:
data.to_csv('data.csv', index=False)

activities

In [61]:
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'

students = pd.read_csv(url)

In [62]:
students = students.fillna(0)

In [63]:
students.head()

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    0.0     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True

In [64]:
#1

students['Extra_points'] = (students['Notas'] * 1.4) - students['Notas']

In [65]:
#2 & 3

students['Final_note'] = students['Notas'] + students['Extra_points']

students['Final_approved'] = students['Final_note'].apply(lambda x: "Yes" if x >= 6 else "Not")

In [66]:
students

         Nome  Idade  Notas  Aprovado  Extra_points  Final_note Final_approved
0         Ary     20    7.5      True          3.00       10.50            Yes
1         Ana     18    0.0     False          0.00        0.00            Not
2       Cátia     27    2.5     False          1.00        3.50            Not
3       Denis     18    5.0     False          2.00        7.00            Yes
4        Beto     21   10.0      True          4.00       14.00            Yes
5       Bruna     23    0.0     False          0.00        0.00            Not
6        Dara     21    7.0      True          2.80        9.80            Yes
7      Carlos     19    6.0      True          2.40        8.40            Yes
8       Alice     35    5.6     False          2.24        7.84            Yes
9       Vitor     28    0.0     False          0.00        0.00            Not
10     Daniel     21    0.0     False          0.00        0.00            Not
11       Igor     24    4.5     False          1.80        6.30            Yes
12  Sthefanie     26    9.5      True          3.80       13.30            Yes
13      Mirla     25    9.0      True          3.60       12.60            Yes
14      Paulo     37    0.0     False          0.00        0.00            Not
15     Mylena     29    7.0      True          2.80        9.80            Yes
16      Lucas     33    0.0     False          0.00        0.00            Not
17      Nadia     34    8.0      True          3.20       11.20            Yes

In [78]:
#4

students.query('Aprovado == False & Final_approved == "Yes"')

     Nome  Idade  Notas  Aprovado  Extra_points  Final_note Final_approved
3   Denis     18    5.0     False          2.00        7.00            Yes
8   Alice     35    5.6     False          2.24        7.84            Yes
11   Igor     24    4.5     False          1.80        6.30            Yes

In [80]:
selecao = (students['Aprovado'] == False) & (students['Final_approved'] == 'Yes')
students[selecao]

     Nome  Idade  Notas  Aprovado  Extra_points  Final_note Final_approved
3   Denis     18    5.0     False          2.00        7.00            Yes
8   Alice     35    5.6     False          2.24        7.84            Yes
11   Igor     24    4.5     False          1.80        6.30            Yes