In [15]:
import pandas as pd

In [16]:
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'
df = pd.read_csv(url, sep=';')

In [17]:
df.isnull()

        Tipo  Bairro  Quartos  Vagas  Suites   Area  Valor  Condominio   IPTU
0      False   False    False  False   False  False  False       False  False
1      False   False    False  False   False  False  False        True   True
2      False   False    False  False   False  False  False       False  False
3      False   False    False  False   False  False  False       False  False
4      False   False    False  False   False  False  False       False   True
...      ...     ...      ...    ...     ...    ...    ...         ...    ...
32955  False   False    False  False   False  False  False       False  False
32956  False   False    False  False   False  False  False       False  False
32957  False   False    False  False   False  False  False       False  False
32958  False   False    False  False   False  False  False       False   True
32959  False   False    False  False   False  False  False       False  False

[32960 rows x 9 columns]

In [18]:
df.isnull().sum()

Tipo              0
Bairro            0
Quartos           0
Vagas             0
Suites            0
Area              0
Valor            17
Condominio     4093
IPTU          10237
dtype: int64

In [19]:
df = dados.fillna(0)

In [20]:
df.isnull().sum()

Tipo          0
Bairro        0
Quartos       0
Vagas         0
Suites        0
Area          0
Valor         0
Condominio    0
IPTU          0
dtype: int64

### Removing Registers

In [21]:
df.query('Valor == 0 | Condominio == 0')

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0
5,Apartamento,Vista Alegre,3,1,0,70,1200.0,0.0,0.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,0.0,0.0
8,Casa de Condomínio,Ramos,2,2,0,65,1000.0,0.0,0.0
10,Apartamento,Centro,1,0,0,36,1200.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
32914,Loja/Salão,Campo Grande,0,0,0,160,2650.0,0.0,0.0
32928,Loja/Salão,Leblon,0,0,0,68,25000.0,0.0,1113.0
32929,Loja/Salão,Freguesia (Jacarepaguá),0,0,0,80,5800.0,0.0,215.0
32931,Casa,Centro,5,0,1,160,5000.0,0.0,80.0
32954,Box/Garagem,Centro,0,0,0,755,14000.0,0.0,0.0

In [22]:
df.query('Valor == 0 | Condominio == 0').index

Index([    1,     5,     7,     8,    10,    16,    18,    31,    35,    76,
       ...
       32893, 32897, 32899, 32911, 32912, 32914, 32928, 32929, 32931, 32954],
      dtype='int64', length=4106)

In [24]:
records_to_remove = df.query('Valor == 0 | Condominio == 0').index

In [30]:
df.drop(records_to_remove, axis=0, inplace=True)

In [33]:
df.drop('Tipo', axis=1, inplace=True)

In [34]:
df

,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Copacabana,1,0,0,40,1700.0,500.0,60.0
2,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Centro,1,0,0,15,800.0,390.0,20.0
4,Higienópolis,1,0,0,48,800.0,230.0,0.0
6,Cachambi,2,0,0,50,1300.0,301.0,17.0
...,...,...,...,...,...,...,...,...
32955,Centro,0,0,0,27,800.0,350.0,25.0
32956,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Leblon,2,0,0,70,3000.0,760.0,0.0
32959,Centro,0,0,0,250,6500.0,4206.0,1109.0

### Filters

In [35]:
df.query("Quartos == 1 & Valor < 1200")

             Bairro  Quartos  Vagas  Suites  Area   Valor  Condominio   IPTU
3            Centro        1      0       0    15   800.0       390.0   20.0
4      Higienópolis        1      0       0    48   800.0       230.0    0.0
28           Tijuca        1      0       0    48   750.0       772.0   25.0
54           Centro        1      0       0    27   750.0       371.0   19.0
94           Centro        1      1       0    37  1100.0       540.0  900.0
...             ...      ...    ...     ...   ...     ...         ...    ...
32714      Botafogo        1      0       0    21  1000.0       282.0   25.0
32763        Glória        1      0       0    10   400.0       107.0   10.0
32818      Flamengo        1      0       0    23   900.0       605.0    0.0
32844        Centro        1      0       0    24  1100.0       323.0    0.0
32950        Tijuca        1      0       0    28  1000.0       360.0   25.0

[835 rows x 8 columns]

In [37]:
selection1 = df['Quartos'] == 1
selection2 = df['Valor'] < 1200

In [39]:
final_selection = (selection1) & (selection2)

In [41]:
df[final_selection]

             Bairro  Quartos  Vagas  Suites  Area   Valor  Condominio   IPTU
3            Centro        1      0       0    15   800.0       390.0   20.0
4      Higienópolis        1      0       0    48   800.0       230.0    0.0
28           Tijuca        1      0       0    48   750.0       772.0   25.0
54           Centro        1      0       0    27   750.0       371.0   19.0
94           Centro        1      1       0    37  1100.0       540.0  900.0
...             ...      ...    ...     ...   ...     ...         ...    ...
32714      Botafogo        1      0       0    21  1000.0       282.0   25.0
32763        Glória        1      0       0    10   400.0       107.0   10.0
32818      Flamengo        1      0       0    23   900.0       605.0    0.0
32844        Centro        1      0       0    24  1100.0       323.0    0.0
32950        Tijuca        1      0       0    28  1000.0       360.0   25.0

[835 rows x 8 columns]

In [42]:
df.query('Quartos >= 2 & Valor < 3000 & Area > 70')

,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
12,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0
21,Tijuca,2,1,0,110,1900.0,700.0,138.0
24,Tijuca,2,1,0,78,2000.0,700.0,0.0
32,Botafogo,2,1,0,76,2500.0,740.0,0.0
36,Recreio dos Bandeirantes,3,1,1,105,2300.0,648.0,0.0
...,...,...,...,...,...,...,...,...
32934,Jacarepaguá,2,1,1,78,2200.0,790.0,180.0
32940,Barra da Tijuca,2,1,1,85,2250.0,1561.0,197.0
32941,Barra da Tijuca,3,2,0,98,2300.0,887.0,177.0
32944,Recreio dos Bandeirantes,3,2,1,88,1550.0,790.0,0.0
32956,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0

or

In [45]:
selection = (df['Quartos'] >= 2) & (df['Valor'] < 3000) & (df['Area'] > 70)
df[selection]

,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
12,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0
21,Tijuca,2,1,0,110,1900.0,700.0,138.0
24,Tijuca,2,1,0,78,2000.0,700.0,0.0
32,Botafogo,2,1,0,76,2500.0,740.0,0.0
36,Recreio dos Bandeirantes,3,1,1,105,2300.0,648.0,0.0
...,...,...,...,...,...,...,...,...
32934,Jacarepaguá,2,1,1,78,2200.0,790.0,180.0
32940,Barra da Tijuca,2,1,1,85,2250.0,1561.0,197.0
32941,Barra da Tijuca,3,2,0,98,2300.0,887.0,177.0
32944,Recreio dos Bandeirantes,3,2,1,88,1550.0,790.0,0.0
32956,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0

In [46]:
df.to_csv('df.csv')

In [50]:
pd.read_csv('df.csv')

,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
2,Centro,1,0,0,15,800.0,390.0,20.0
3,Higienópolis,1,0,0,48,800.0,230.0,0.0
4,Cachambi,2,0,0,50,1300.0,301.0,17.0
...,...,...,...,...,...,...,...,...
28849,Centro,0,0,0,27,800.0,350.0,25.0
28850,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
28851,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
28852,Leblon,2,0,0,70,3000.0,760.0,0.0
28853,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [49]:
df.to_csv('df.csv', index=False)

In [51]:
pd.read_csv('df.csv')

,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
2,Centro,1,0,0,15,800.0,390.0,20.0
3,Higienópolis,1,0,0,48,800.0,230.0,0.0
4,Cachambi,2,0,0,50,1300.0,301.0,17.0
...,...,...,...,...,...,...,...,...
28849,Centro,0,0,0,27,800.0,350.0,25.0
28850,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
28851,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
28852,Leblon,2,0,0,70,3000.0,760.0,0.0
28853,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [52]:
df.to_csv('df.csv', index=False, sep=';')

In [54]:
pd.read_csv('df.csv', sep=';')

,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
2,Centro,1,0,0,15,800.0,390.0,20.0
3,Higienópolis,1,0,0,48,800.0,230.0,0.0
4,Cachambi,2,0,0,50,1300.0,301.0,17.0
...,...,...,...,...,...,...,...,...
28849,Centro,0,0,0,27,800.0,350.0,25.0
28850,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
28851,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
28852,Leblon,2,0,0,70,3000.0,760.0,0.0
28853,Centro,0,0,0,250,6500.0,4206.0,1109.0

Activities

In [ ]:
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'

data = pd.read_csv(url)

In [66]:
data.query('Nome == "Alice"')

    Nome  Idade  Notas  Aprovado
8  Alice     35    5.6     False

In [59]:
#1

data = data.fillna(0)
data

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    0.0     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    0.0     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    0.0     False
10     Daniel     21    0.0     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    0.0     False
15     Mylena     29    7.0      True
16      Lucas     33    0.0     False
17      Nadia     34    8.0      True

In [71]:
#2

remove = data.query('Nome == "Alice" | Nome == "Carlos"').index

In [74]:
data.drop(index=remove, inplace=True)

In [76]:
#3

approved_students = data.query('Aprovado == True')

In [77]:
#4

approved_students.to_csv('approved_students.csv', index=False)

In [90]:
#extra

approved_students

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
4        Beto     21   10.0      True
6        Dara     21    7.0      True
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
15     Mylena     29    7.0      True
17      Nadia     34    8.0      True

In [93]:
approved_students = approved_students.replace(7.0, 8.0)